### ISSUE TITLE
Deploy externally defined contracts

### ISSUE THREAD

**Issue by jdbranham** [bjartek/overflow#67] opened 2022-08-11 07:42 UTC
**Is your feature request related to a problem? Please describe.**
I'm working on a contract that has a dependency chain of contracts, using the flow emulator for tests.  
Some new functionality I'm creating depends on contracts in a different project.  
I'd rather not copy the contracts into my project because they may get out of sync.  

**Describe the solution you'd like**
It would be great if I could configure the test to pull in the external contracts at runtime.  
Potentially from main/test-net

**Describe alternatives you've considered**
Copying the contracts into the project would work, but they may get out of sync.  
I could download the contract files from the other repo and deploy them as part of a test setup - but they are in a private repo.  

I'm a flow noob, but point me in the right direction and I'd be happy to contribute to this feature.

**Comment by jdbranham** [comment] 2022-08-11 20:23
Thinking more about this... would it make sense to have this a function of the emulator itself?

**Comment by bjartek** [comment] 2022-08-11 21:07
Hey been travelling so could not respond before. The problem is that you want that contract to be there when developing as well, since you want the LSP to get it and give you help on its methods as well. For direct depdencenies that is. For indirect dependencies I just think the effort is not worth it to do it differently. 

So what i propose is that in the setup of a project phase you can specify in flow.json what contract you want to import and then it will read from that location and download it to a speciffied place and add it to flow.json. There should also be functionality to check if contracts that are downloaded are changed. And show the diff, this is also useful for your own contracts.

**Comment by jdbranham** [comment] 2022-08-11 22:38
That makes sense - and the syntax completion would be ideal.
Curious then if the `flow.json` had a `dependencies` section like a `package.json` that could download them to a transient location, so the `contracts` entries could reference the transient folder.

flow-cli then might do something like npm...
```
flow emulator add-dep Hello@0x01 --network=testnet
```

**Comment by bjartek** [comment] 2022-08-11 23:34
Flow.json has a contracts block with location and alias. Checking if code in aliases/location is the same and enable options around that is not rocket science. The code can be dled from chain with flow-cli

**Comment by bjartek** [comment] 2024-02-15 12:23
I am going to close this as flow-cli has now commands to add contracts to flow json and overflow will just deploy those.

**Closed as completed by bjartek** 2024-02-15 12:23 UTC
